version: "3.8"
services:
    php8:
        container_name: rabbitmq-php
        build: docker
        ports:
            - "8001:8000"
        volumes:
            - ./:/var/www
        networks:
          - dev
    rabbitmq:
        image: rabbitmq:3.7-management
        container_name: rabbit_mq
        ports:
            # AMQP protocol port
            - 5672:5672
            # HTTP management UI
            - 15672:15672
        networks:
            - dev
networks:
    dev:
volumes:
    db-data: